stages:
  - trigger-deploy

trigger-deploy:
  image: ubuntu
  stage: trigger-deploy
  only:
    - github-release
  script:
    - echo "Triggering Maven Deploy Repository..."
    - apt-get update && apt-get install -y curl
    - curl -X POST "https://git.nosi.cv/api/v4/projects/${GITLAB_DEPLOY_PROJECT_ID}/trigger/pipeline" \
      --form "token=$GITLAB_DEPLOY_TOKEN" \
      --form "ref=deploy" \
      --form "variables[LIBRARY_NAME]=${CI_PROJECT_NAME}"